language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t astinchoi/docker-react -f Dockerfile.dev .

script:
  # - docker run astinchoi/docker-react npm run test -- --coverage
  - docker run -e CI=true astinchoi/docker-react npm run test
## docker build -f Dockerfile.dev .
## docker run -it 1000e30547a3 npm run test -- --coverage
