language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t astinchoi/docker-react -f Dockerfile.dev .

script:
  # - docker run astinchoi/docker-react npm run test -- --coverage
  - docker run -e CI=true astinchoi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-046485750416"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
####
# docker build -f Dockerfile.dev .
# docker run -it 1000e30547a3 npm run test -- --coverage

