version: "3"
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]
#######
# React App Exited With Code 0
# 4-1-2020

# Recently, a bug was introduced with the latest Create React App version that is causing the React app to exit when starting with Docker Compose.

# To Resolve this:

# Add stdin_open property to your docker-compose.yml file

#   web:
#     stdin_open: true
# Make sure you rebuild your containers after making this change with  docker-compose down && docker-compose up --build

# https://github.com/facebook/create-react-app/issues/8688

# https://stackoverflow.com/questions/60790696/react-scripts-start-exiting-in-docker-foreground-cmd

# Windows not Detecting Changes - Docker Compose
# updated 4-21-2020

# If you are using any version of Windows and your React app is not automatically reloading after a code change, you can add this environment variable to your compose file:

# services:
#   web:
#     environment:
#       - CHOKIDAR_USEPOLLING=true
